site_name: Peers Program Portal
theme:
  name: 'slate'

nav:
  - Home: index.md
  - About:
      - Mission: about/mission.md
      - Operations: about/operations.md
  - Node Operation:
      - Setup Guide: node/setup.md
      - FAQ: node/faq.md
  - Community:
      - Join Discord: community/discord.md
      - Member List: community/members.md
  - Resources:
      - References: resources/links.md
  - News & Updates: news/index.md
