site_name: Peers Program Portal
theme:
  name: 'slate'

nav:
  - README: ./program.md
  - Updates: updates/index.md
  - Build:
      - Setup Guide: node/setup.md
      - FAQ: node/faq.md
  - Community:
      - Join Discord: community/discord.md
      - Member List: community/members.md
  - Resources:
      - Links: resources/links.md
