site_name: Astar Peers Program
theme:
  #name: material
  #name: readthedocs
  #name: 'darkly'
  name: 'slate'

nav:
  - README:
      - About Program: ./program.md
      - Updates: ./updates.md
  - Build:
      - Setup Guide: node/setup.md
      - FAQ: node/faq.md
  - Community:
      - Application: community/application.md
      - Join Discord: community/discord.md
      - Peers: community/peers.md
  - Resources:
      - Links: resources/links.md
